create table cliente (
	cod_cliente INT,
	genero_cliente VARCHAR(50),
	nome_cliente VARCHAR(50),
	dt_nascimento DATE,
	bairro VARCHAR(27)
);
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (1, 'F', 'Eleanora McFayden', '1974/11/19', 'Tenente Jardim');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (2, 'M', 'Karita Billany', '1984/10/09', 'Charitas');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (3, 'M', 'Robinetta Spraging', '1973/05/08', 'Gramacho');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (4, 'M', 'Rosita Dybald', '1998/03/27', '25 de agosto');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (5, 'F', 'Eugenio Manueli', '1980/09/25', 'Jardim São Lourenço');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (6, 'F', 'Bobbie Melchior', '1982/12/06', '25 de agosto');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (7, 'F', 'Dolph Astall', '1970/05/27', '25 de agosto');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (8, 'F', 'Dorice Rosoni', '1988/10/24', 'Jardim São Lourenço');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (9, 'M', 'Ruperto Schriren', '1993/04/15', '25 de agosto');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (10, 'F', 'Cecil Lafranconi', '1975/07/30', 'Gramacho');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (11, 'M', 'Hadlee Small', '1974/03/02', '25 de agosto');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (12, 'M', 'Delainey Sporgeon', '1987/12/02', 'Jardim Nossa Sra das Graças');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (13, 'F', 'Horace Treadgall', '1996/03/03', 'Charitas');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (14, 'M', 'Rafaello Anthiftle', '2000/04/10', 'Tenente Jardim');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (15, 'F', 'Neils Succamore', '1996/11/28', 'Tenente Jardim');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (16, 'F', 'Abbey Fawssett', '1985/07/20', 'Tenente Jardim');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (17, 'F', 'Malina Benthall', '1996/11/18', '25 de agosto');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (18, 'M', 'Zak Richardt', '1988/10/14', 'Vila Actura');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (19, 'F', 'Alphard Mallindine', '1998/11/16', '25 de agosto');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (20, 'M', 'Ardyce Soppeth', '1979/12/20', 'Bela Vista');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (21, 'M', 'Belicia Godfery', '1985/02/12', 'Charitas');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (22, 'M', 'Frannie Ledur', '2000/02/14', '25 de agosto');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (23, 'F', 'Porty Doxsey', '1977/01/02', '25 de agosto');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (24, 'F', 'Daune Smowton', '1989/06/16', '25 de agosto');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (25, 'M', 'Lawton MacGow', '1970/10/27', '25 de agosto');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (26, 'M', 'Calypso Arran', '1970/10/11', 'Santa Bárbara');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (27, 'M', 'Ranee Deighton', '1993/10/29', 'Jardim Nossa Sra das Graças');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (28, 'M', 'Roman Daville', '1975/08/30', 'Tenente Jardim');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (29, 'M', 'Lin Boldt', '1971/08/13', '25 de agosto');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (30, 'M', 'Tremain Maith', '1998/05/05', 'Tenente Jardim');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (31, 'M', 'Enid Rothman', '1978/04/30', 'Jardim Iguaçu');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (32, 'M', 'Bartlet Van Leijs', '1971/01/23', 'Bela Vista');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (33, 'F', 'Marena Karolewski', '1996/03/19', '25 de agosto');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (34, 'M', 'Ashely Lorne', '1997/06/25', 'Jardim Nossa Sra das Graças');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (35, 'F', 'Job Crudgington', '1990/12/25', 'Vila Actura');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (36, 'F', 'Sonja Duffyn', '2000/08/21', 'Jardim Nossa Sra das Graças');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (37, 'F', 'Shaughn Pyner', '1996/11/03', 'Santa Bárbara');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (38, 'M', 'Velma Brodeur', '1982/07/22', 'Jardim Nossa Sra das Graças');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (39, 'M', 'Niles Toffolo', '1994/08/23', '25 de agosto');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (40, 'F', 'Gardener Parrin', '1971/11/16', '25 de agosto');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (41, 'M', 'Bettine Kneesha', '2001/12/09', 'Jardim Iguaçu');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (42, 'M', 'Gustavus Godfery', '1984/02/16', '25 de agosto');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (43, 'F', 'Alexandrina Collard', '1978/08/30', '25 de agosto');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (44, 'M', 'Pearce Gorhardt', '1993/03/04', '25 de agosto');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (45, 'M', 'Chandra Jewis', '1970/12/04', 'Jardim São Lourenço');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (46, 'F', 'Tonnie Attrill', '1992/12/30', 'Jardim São Lourenço');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (47, 'M', 'Shayne O''Mannion', '1985/11/20', 'Bela Vista');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (48, 'M', 'Christi Plenty', '1972/09/21', 'Jardim Nossa Sra das Graças');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (49, 'F', 'Moise Lendon', '1990/04/23', '25 de agosto');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (50, 'F', 'Christen Summerson', '1981/06/08', 'Charitas');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (51, 'F', 'Toma Peartree', '1975/03/06', 'Tenente Jardim');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (52, 'M', 'Estelle Wickrath', '1973/05/01', 'Gramacho');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (53, 'F', 'Dotty Andreini', '1970/12/01', 'Jardim Nossa Sra das Graças');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (54, 'M', 'Kingsley Warton', '1978/03/06', 'Vila Actura');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (55, 'F', 'Grazia Kedge', '1994/04/25', '25 de agosto');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (56, 'F', 'Brianna Vasentsov', '1971/10/07', '25 de agosto');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (57, 'F', 'Verene Rogez', '1994/12/29', 'Vila Actura');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (58, 'F', 'Aurea Filson', '1974/12/19', 'Charitas');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (59, 'F', 'Enrique Rourke', '1994/06/08', '25 de agosto');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (60, 'M', 'Eugenia Athridge', '1991/03/03', 'Jardim Nossa Sra das Graças');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (61, 'F', 'Frederique Jirek', '1994/07/25', 'Jardim Iguaçu');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (62, 'F', 'Oswell Dunkerly', '2001/02/20', '25 de agosto');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (63, 'M', 'Perri Rhoades', '1972/02/05', 'Gramacho');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (64, 'F', 'Tyrone Wagstaffe', '1978/12/23', 'Charitas');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (65, 'M', 'Kit Patkin', '2002/04/23', 'Vila Actura');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (66, 'F', 'Zachary Winthrop', '1999/03/09', 'Jardim Iguaçu');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (67, 'M', 'Toinette Spincks', '1990/08/20', 'Jardim Iguaçu');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (68, 'M', 'Rochella Harkin', '1974/07/16', '25 de agosto');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (69, 'F', 'Reade Bringloe', '1984/02/05', 'Gramacho');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (70, 'M', 'Gil Flacknoe', '1988/07/06', 'Jardim Iguaçu');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (71, 'M', 'Teodorico Hame', '1971/07/07', 'Charitas');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (72, 'F', 'Cazzie Randleson', '1991/12/13', 'Charitas');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (73, 'F', 'Kerry Kieran', '1990/04/26', '25 de agosto');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (74, 'F', 'Elle Wherton', '1971/07/03', 'Jardim São Lourenço');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (75, 'F', 'Costa Issacoff', '1977/05/06', '25 de agosto');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (76, 'M', 'Melantha Yackiminie', '1996/05/12', '25 de agosto');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (77, 'M', 'Isadora MacRorie', '1984/02/23', 'Charitas');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (78, 'F', 'Adria Palek', '1991/03/23', '25 de agosto');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (79, 'M', 'Trevor Rippon', '1976/05/25', 'Tenente Jardim');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (80, 'F', 'Petr Scadding', '1984/09/25', '25 de agosto');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (81, 'M', 'Dale Steinson', '2000/10/18', 'Gramacho');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (82, 'M', 'Prudence Goodenough', '1997/12/22', 'Bela Vista');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (83, 'M', 'Dolly Becket', '1994/03/02', '25 de agosto');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (84, 'M', 'Creighton Renforth', '1992/03/15', 'Santa Bárbara');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (85, 'F', 'Fabien Birtonshaw', '1997/06/12', 'Charitas');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (86, 'M', 'Gale Forman', '1996/10/09', '25 de agosto');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (87, 'F', 'Honoria Gaylor', '1999/03/08', 'Charitas');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (88, 'M', 'Dinah Opdenort', '1983/01/17', '25 de agosto');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (89, 'M', 'Elonore Tillard', '1977/07/29', 'Vila Actura');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (90, 'F', 'Dulcea Pregal', '1986/12/30', 'Tenente Jardim');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (91, 'M', 'Raddy Thomsson', '1978/02/08', '25 de agosto');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (92, 'F', 'Cindie Eales', '2002/03/05', 'Jardim São Lourenço');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (93, 'F', 'Samson McKague', '1978/05/31', 'Santa Bárbara');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (94, 'F', 'Bent Miguet', '1990/03/30', 'Vila Actura');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (95, 'M', 'Marina Sentance', '1977/03/18', 'Charitas');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (96, 'F', 'Jewell Bickmore', '1972/10/14', 'Vila Actura');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (97, 'F', 'Silvano Petti', '1993/10/07', 'Vila Actura');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (98, 'F', 'Birch Twyford', '1996/09/16', 'Charitas');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (99, 'F', 'Raquela Dilworth', '1997/08/28', 'Jardim Iguaçu');
insert into cliente (cod_cliente, genero_cliente, nome_cliente, dt_nascimento, bairro) values (100, 'M', 'Gwendolyn Thrower', '1973/05/07', 'Jardim Iguaçu');
